# Generated by Django 4.1.7 on 2023-03-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("d", "Draft"), ("p", "Published")], default="d", max_length=1
            ),
        ),
    ]
