# Generated by Django 4.1.7 on 2023-03-20 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_comment_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
    ]
